### ISSUE TITLE
HL7 entities URI problem

### ISSUE THREAD

**Issue by leetal** [cts2/lexevs-service#8]
Hi again! 

So, i just loaded (successfully) the HL7 core mif. Upon traversing the data, it came to a quick halt when i realized that i could not query any given entity. This seems to be due to the URI having an extra ":" in it that is parsed as "%3A" encoded.
HL7 have colons in their names and this seems to mess up the URL routing in lexevs-service. 
If i try a code in HL7 without a colon, it works as expected.

URI: `http(s)://[ADDRESS]:[PORT]/codesystem/[CS]/version/[VERSION]/entity/[NAMESPACE]:[CODE]`
Example: `http://127.0.0.1:8080/lexevs-service/codesystem/1189-20121121/version/DEFN=UV=VO=1189-20121121/entity/HL7:20042%3ADSC`
**_Notice the format of the namespace and code._**

Below are some screenshots to clarify.

**Working example:**
<img width="1418" alt="screen shot 2016-08-18 at 10 01 50" src="https://cloud.githubusercontent.com/assets/1221839/17766306/d7f969de-652a-11e6-92d8-5311d8fb84a8.png">

**Error given when requesting an entity with colon:**
<img width="1422" alt="screen shot 2016-08-18 at 09 38 26" src="https://cloud.githubusercontent.com/assets/1221839/17765667/97f0d456-6527-11e6-8cce-cf6809ea3c67.png">

**How data is stored in DB:**
<img width="1159" alt="screen shot 2016-08-18 at 09 48 25" src="https://cloud.githubusercontent.com/assets/1221839/17765970/07dfbcb8-6529-11e6-972a-382d549972ce.png">

Is this the expected behavior or a bug?

// Alex

**Comment by hsbauer** [comment]
Hi Alexander:

I'm seeing this in our production service as well.  This is a bug.  I'm going to create an Issue against it with our sponsors.

**Comment by hsbauer** [comment]
Our sponsors have given us the go ahead to provide a fix for this.  Hopefully, you'll be hearing from us soon.

**Comment by hsbauer** [comment]
Hi Alexander:

We have a fix that can be checked out from github as a tag:
https://github.com/cts2/lexevs-service/tree/1.5.1.FINAL

Later today we'll be able to provide links to a war file if that's what you prefer.  

-scott

**Comment by leetal** [comment]
Thought i'd drop by and say that the update has fixed the issue. Thank you!

**Comment by hsbauer** [comment]
Thanks for letting us know and for closing your issue. If you'd like to share anything about your project here or offline, we'd be interested in your use case.

**Comment by leetal** [comment]
Actually, i'm having trouble to understand how to insert own entries and map them to each others in LexEVS.

My use-case is quite simple:
I have 2..N different vocabularies that i need to insert (currently on textual form) into LexEVS. These have all different codes for more or less the same term (they can have the same code as well for some of them). I have spent more or less three days now trying to figure out how to create codingScheme(s) for this (i reckon i only need one codingScheme), and set up the mappings and of course insert the entries into LexEVS using LexGRID xml representation. 

See below for a simplified example of what i'm after.

Ex: 

| Vocabulary | Code | Textual representation |
| ------------- | ------------- | ----- |
| Vocabulary 1 | 11000 | Banana |
| Vocabulary 1 | 11001 | Orange |
| Vocabulary 1 | 11002 | Kiwi | 
| Vocabulary 2 | abc1 | Banana |
| Vocabulary 2 | abc2 | Orange |
| Vocabulary 2 | abc3 | Kiwi |  
| Vocabulary 3 | zzz1 | Banana |
| Vocabulary 3 | abc2 | Orange |
| Vocabulary 3 | zzz3 | Kiwi | 
| Own, internal vocabulary | 1 | Banana |
| Own, internal vocabulary | 2 | Orange |
| Own, internal vocabulary | 3 | Kiwi | 

Effectively what i'm after is that if i ask for mappings to Vocabulary 2 with the code **11000** in Vocabulary 1, i would receive entity data about **abc1**. The inverse must work as well.

The same would go from my internal vocabulary: If i ask for mappings to any one vocabulary (1 to 3) with my own internal codes, the co-responding code for that vocabulary should be fetched.

I have looked at all the examples and the one that is closest is the Automobiles examples. But i have still not managed to get that example up and running. I have tried to insert example data into LexEVS and then i try to query that data in lexevs-service, but i always got an exception. So i skipped that (for now), and wanted to just insert own data first into LexEVS, complete with mappings and all. Fruits seemed like a good analogue.

Sorry for the long post, but i hope you can shed some light on this use-case. 

Regards
Alexander W

**Comment by hsbauer** [comment]
I'm not sure which part of this isn't working for you Alexander.  Are you having trouble loading the original coding schemes you created (Is the load failing?) or are you having trouble creating a map between the schemes.  If you have cloned or installed the lexevs project set you can find a LexGrid xml mapping example in the the lbTest project or test folder under resources/testData/testMapping.xml

**Comment by leetal** [comment]
It's more of a "finding what to do where" problem. But I'll definitely have
a look at that example and see if I can get it working from that. :)

**Comment by hsbauer** [comment]
This may be of some help:
https://wiki.nci.nih.gov/display/LexEVS/5+-+Advanced+LexEVS+6.0+Vocabulary+Administration#id-5-AdvancedLexEVS6.0VocabularyAdministration-AuthoringCodingSchemesandtheirChildElements

**Comment by leetal** [comment]
Thanks for the input! I just now got a data model working with mappings one-to-one.
One thing that crossed my mind is that i can specify multiple relations in the LexGRID models and even load these into LexEVS. But lexevs-service seems to not really like that, throwing exceptions saying that only one relations field is allowed.

My question now is how do i create mappings in the form of "one-to-many"? Or is this not supported by lexevs-service? A "many-to-one" can easily be achieved by just creating multiple mapping files pointing to the same codesystem/namespace. But as i tried to explain yesterday, i need to be able to map one codesystem to many. Any thought on how to achieve this? Do i really need to create a separate mapping file for each "mapping direction (to/from)"?

I just need to thank you once again for helping me this much.

**Comment by hsbauer** [comment]
There are limits to what can be done with mapping in LexEVS.  We do have some interest in expanding our mapping capabilities, but I can't guarantee it will be quite what you have in mind.  Can you pass along your stack trace?  I'd like to be sure that you are hitting a limitation of the mapping architecture and there isn't some problem with your mapping scheme.

**Comment by leetal** [comment]
Yes, i think this probably is a limitation since the error message is so informative: 
```
java.lang.IllegalArgumentException: Only ONE Relations container is allowed in a Mapping Coding Scheme.
        at org.springframework.util.Assert.isTrue(Assert.java:65)
        at edu.mayo.cts2.framework.plugin.service.lexevs.service.mapversion.CodingSchemeToMapVersionTransform.getFromToCodingSchemes(CodingSchemeToMapVersionTransf
orm.java:150)
        at edu.mayo.cts2.framework.plugin.service.lexevs.service.mapversion.CodingSchemeToMapVersionTransform.transformFullDescription(CodingSchemeToMapVersionTran
sform.java:92)
        at edu.mayo.cts2.framework.plugin.service.lexevs.service.mapversion.LexEvsMapVersionReadService.transform(LexEvsMapVersionReadService.java:68)
        at edu.mayo.cts2.framework.plugin.service.lexevs.service.mapversion.LexEvsMapVersionReadService.transform(LexEvsMapVersionReadService.java:43)
        at edu.mayo.cts2.framework.plugin.service.lexevs.service.AbstractLexEvsCodeSystemService.getByVersionIdOrTag(AbstractLexEvsCodeSystemService.java:65)
        at edu.mayo.cts2.framework.plugin.service.lexevs.service.mapversion.LexEvsMapVersionReadService.read(LexEvsMapVersionReadService.java:114)
        at edu.mayo.cts2.framework.plugin.service.lexevs.service.mapversion.LexEvsMapVersionReadService.read(LexEvsMapVersionReadService.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at edu.mayo.cts2.framework.webapp.service.AbstractServiceAwareBean$1.invoke(AbstractServiceAwareBean.java:125)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
        at com.sun.proxy.$Proxy60.read(Unknown Source)
        at edu.mayo.cts2.framework.webapp.rest.controller.AbstractMessageWrappingController.doRead(AbstractMessageWrappingController.java:299)
        at edu.mayo.cts2.framework.webapp.rest.controller.MapVersionController.getMapVersionByName(MapVersionController.java:479)
        at edu.mayo.cts2.framework.webapp.rest.controller.MapVersionController$$FastClassByCGLIB$$9a17962f.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
        at edu.mayo.cts2.framework.webapp.rest.controller.MapVersionController$$EnhancerByCGLIB$$a7d633ef.getMapVersionByName(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:436)
        at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:424)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:900)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:827)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at edu.mayo.cts2.framework.webapp.rest.filter.AcceptHeaderAdjustingFilter.doFilter(AcceptHeaderAdjustingFilter.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at edu.mayo.cts2.framework.webapp.rest.filter.AcceptHeaderAdjustingFilter.doFilter(AcceptHeaderAdjustingFilter.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at edu.mayo.cts2.framework.webapp.rest.filter.jsonp.JsonpCallbackFilter.doFilter(JsonpCallbackFilter.java:95)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at edu.mayo.cts2.framework.webapp.rest.osgi.OsgiExtensionPointFilterProxy.doFilter(OsgiExtensionPointFilterProxy.java:94)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hsbauer** [comment]
Just so I understand your mapping scheme -- are you trying to separate relationships to different coding schemes into different relations containers?

**Comment by leetal** [comment]
Basically yes. Instead of using multiple files (if even possible). 

Here is the mappings file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<codingScheme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://LexGrid.org/schema/2010/01/LexGrid/codingSchemes  http://LexGrid.org/schema/2010/01/LexGrid/codingSchemes.xsd"
    xmlns="http://LexGrid.org/schema/2010/01/LexGrid/codingSchemes"
    xmlns:lgBuiltin="http://LexGrid.org/schema/2010/01/LexGrid/builtins"
    xmlns:lgCommon="http://LexGrid.org/schema/2010/01/LexGrid/commonTypes"
    xmlns:lgCon="http://LexGrid.org/schema/2010/01/LexGrid/concepts"
    xmlns:lgRel="http://LexGrid.org/schema/2010/01/LexGrid/relations"
    xmlns:lgCS="http://LexGrid.org/schema/2010/01/LexGrid/codingSchemes"
    xmlns:lgLDAP="http://LexGrid.org/schema/2010/01/LexGrid/ldap"
    xmlns:lgNaming="http://LexGrid.org/schema/2010/01/LexGrid/naming"
    xmlns:lgService="http://LexGrid.org/schema/2010/01/LexGrid/service"
    xmlns:lgVD="http://LexGrid.org/schema/2010/01/LexGrid/valueDomains"
    xmlns:lgVer="http://LexGrid.org/schema/2010/01/LexGrid/versions"
    approxNumConcepts="0" codingSchemeName="TESTInternalMapping" defaultLanguage="en" formalName="TEST Internal Mapping" codingSchemeURI="urn:TEST:internal:mapping" representsVersion="1.0">
    <lgCommon:entityDescription>TEST Internal Mapping</lgCommon:entityDescription>
    <localName>TEST:internal:mapping</localName>
    <localName>TEST Internal Mapping</localName>
    <localName>TESTInternalMapping</localName>
    <source subRef="internalMappingSubRef" role="internalMappingRole">asd</source>
    <copyright>asd</copyright>
    <mappings>
        <lgNaming:supportedAssociation localId="mapsTo" uri="urn:TEST:internal:mapping:mapsto">mapsTo</lgNaming:supportedAssociation>
        <lgNaming:supportedCodingScheme localId="TESTInternalMapping" uri="urn:TEST:internal:mapping">TESTInternalMapping</lgNaming:supportedCodingScheme>
        <lgNaming:supportedCodingScheme localId="TESTInternalTerminology" uri="urn:TEST:internal:terminology">TESTInternalTerminology</lgNaming:supportedCodingScheme>
        <lgNaming:supportedCodingScheme localId="TESTExternalHospital1Terminology" uri="urn:TEST:external:hos1:terminology">TESTExternalHospital1Terminology</lgNaming:supportedCodingScheme>
        <lgNaming:supportedCodingScheme localId="TESTExternalHospital2Terminology" uri="urn:TEST:external:hos2:terminology">TESTExternalHospital2Terminology</lgNaming:supportedCodingScheme>
        <lgNaming:supportedContainerName localId="Hospital1relations">InternalToExternalHospital1Mappings</lgNaming:supportedContainerName>
        <!--<lgNaming:supportedContainerName localId="Hospital2relations">InternalToExternalHospital2Mappings</lgNaming:supportedContainerName>-->
        <lgNaming:supportedDataType localId="textplain">text/plain</lgNaming:supportedDataType>
        <lgNaming:supportedLanguage localId="en" uri="www.en.org/english">en</lgNaming:supportedLanguage>
        <lgNaming:supportedLanguage localId="se" uri="www.se.org/svenska">se</lgNaming:supportedLanguage>
        <lgNaming:supportedNamespace localId="TESTInternalTerminology" uri="urn:TEST:internal:terminology" equivalentCodingScheme="TESTInternalTerminology">TESTInternalTerminology</lgNaming:supportedNamespace>
        <lgNaming:supportedNamespace localId="TESTExternalHospital1Terminology" uri="urn:TEST:external:hos1:terminology" equivalentCodingScheme="TESTExternalHospital1Terminology">TESTExternalHospital1Terminology</lgNaming:supportedNamespace>
        <lgNaming:supportedNamespace localId="TESTExternalHospital2Terminology" uri="urn:TEST:external:hos2:terminology" equivalentCodingScheme="TESTExternalHospital2Terminology">TESTExternalHospital2Terminology</lgNaming:supportedNamespace>
        <lgNaming:supportedProperty localId="definition">definition</lgNaming:supportedProperty>
        <lgNaming:supportedSource localId="asd">asd</lgNaming:supportedSource>
        <lgNaming:supportedSource localId="hospital1.com">hospital1.com</lgNaming:supportedSource>
        <lgNaming:supportedSource localId="hospital2.com">hospital2.com</lgNaming:supportedSource>
    </mappings>
    <entities/>
    <relations representsVersion="1.0" containerName="InternalToExternalHospital1Mappings" isMapping="true" 
        sourceCodingScheme="TESTInternalTerminology" sourceCodingSchemeVersion="1.0" 
        targetCodingScheme="TESTExternalHospital1Terminology" targetCodingSchemeVersion="1.0">
        <lgRel:associationPredicate associationName="mapsTo">
            <lgRel:source sourceEntityCodeNamespace="TESTInternalTerminology" sourceEntityCode="00001">
                <lgRel:target targetEntityCodeNamespace="TESTExternalHospital1Terminology" targetEntityCode="abc001" />
            </lgRel:source>
            <lgRel:source sourceEntityCodeNamespace="TESTInternalTerminology" sourceEntityCode="00002">
                <lgRel:target targetEntityCodeNamespace="TESTExternalHospital1Terminology" targetEntityCode="abc002" />
            </lgRel:source>
            <lgRel:source sourceEntityCodeNamespace="TESTInternalTerminology" sourceEntityCode="00003">
                <lgRel:target targetEntityCodeNamespace="TESTExternalHospital1Terminology" targetEntityCode="abc003" />
            </lgRel:source>
        </lgRel:associationPredicate>
    </relations>
    <!--<relations representsVersion="1.0" containerName="InternalToExternalHospital2Mappings" isMapping="true" sourceCodingScheme="TESTInternalTerminology" targetCodingScheme="TESTExternalHospital2Terminology">
        <lgRel:associationPredicate associationName="mapsTo">
            <lgRel:source sourceEntityCodeNamespace="TESTInternalTerminologyNS" sourceEntityCode="00001">
                <lgRel:target targetEntityCodeNamespace="TESTExternalHospital2TerminologyNS" targetEntityCode="zzz001" />
            </lgRel:source>
            <lgRel:source sourceEntityCodeNamespace="TESTInternalTerminologyNS" sourceEntityCode="00002">
                <lgRel:target targetEntityCodeNamespace="TESTExternalHospital2TerminologyNS" targetEntityCode="zzz002" />
            </lgRel:source>
            <lgRel:source sourceEntityCodeNamespace="TESTInternalTerminologyNS" sourceEntityCode="00003">
                <lgRel:target targetEntityCodeNamespace="TESTExternalHospital2TerminologyNS" targetEntityCode="zzz003" />
            </lgRel:source>
        </lgRel:associationPredicate>
    </relations>-->
</codingScheme>
```

This is basically what i want to do but of course uncomment the last relations entry. 
There is far more elements in it right now than is needed, but i'll clean that up later. ;)

**Comment by hsbauer** [comment]
Ok, I'm going to discuss a possible workaround with a colleague.  You may be stuck with multiple mappings, but if you are creating your own code systems there may be some flexibility with creating multiple references within a code system to map to.  If not I'll see if we can't lump this use case with some other mapping upgrades we have in the pipeline.

**Comment by leetal** [comment]
Sounds great! I'l continue on my side to find a suitable solution as well. Of course, if i create multiple mappings, one for each direction it will probably "work", but a more neat solution would be to reference multiple code systems from one mapping relation.

**Comment by kevinpeterson** [comment]
Sounds like you're doing some interesting stuff. A little background on mappings in LexEVS:

The LexEVS model was from the start designed to allow cross-coding scheme relationships. But as you've noticed, there really isn't a specific modeling for a "Mapping" in LexEVS. The LexEVS CodingScheme model (with a few minor changes) was able to represent the information, but we had to make some choices. For example, how exactly do we define a "Mapping" in LexEVS and how is it different than just a normal CodingScheme? One of the decisions that was made, as you've seen, is to assert that a Mapping is a CodingScheme with a single relations container that has from/to CodingSchemes. We did this because the API treats Mapping CodingSchemes slightly differently, and we had to put some constraints on how they could be modeled so that the API knew what to expect.

It would be possible to extend this idea to allow multiple relations containers. That probably wouldn't cause problems, but we don't support it now. The model can handle it -- you could create LexGrid XML to do that now, but the API doesn't. You probably do have some options even as things sit now, and I think the team here will have some ideas for you.

**Comment by hsbauer** [comment]
You can try a workaround we think should work if you juggle namespaces for terminology sets.  It's possible, for instance, to resolve an entity defined in one code system that points to the namespace of another code system (So long as that system is defined in the supported attributes and exists in the terminology service)  So you could create your 3 code systems as described above, then refer to each as supported namespaces and coding schemes in a fourth system defining some version of the entities you want to map to by the namespace of the outside code system.  Finally you can use the source terminology (the source of your one for the one to many relationship) and create a mapping scheme between this and this composite terminology with the references to the three others.  The critical step is to create a supported namespace and a supported coding scheme that namespace points to as a referenced coding scheme for any of the 3 code systems you want to refer to.  This still requires one extra coding scheme beyond the mapping scheme which would be the "composite scheme."  We haven't tried this, but it should work.  This may not be clear, but feel free to ask questions.

**Comment by leetal** [comment]
Thanks for the input! I'll try the workaround today (if i can squeeze it in between all meetings) and see if i can come up with a working solution. If i do, i'll post it here for future reference.

**Comment by leetal** [comment]
So, seems i cannot get this right anyways.. I'm probably more the cause of this than LexEVS. 
 If i query:
`[BASE URL]/map/BFTInternalToExternalMapping/version/BFTInternalToExternalMapping-1.0/entry/BFTInternalTerminology:00001` 
i only get one mapping result (abc001) instead of the wanted two (abc001 + zzz001).

I have attached a complete set of data (codeschemes and mapping) if you want to take a look and see if i totally misunderstood the task or if there is anything else thats hindering this from working. Notice that there is only two sets of "external" data instead of three as above for simplicity.

[data_sets.zip](https://github.com/cts2/lexevs-service/files/446830/data_sets.zip)
